# Generated by Django 4.0.4 on 2022-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforceaccount',
            name='role_type',
            field=models.CharField(choices=[('Device', 'Device'), ('Member', 'Member')], default='Device', max_length=10),
        ),
    ]
