# Generated by Django 4.0.4 on 2022-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_taskforceaccount_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforceaccount',
            name='role_type',
            field=models.CharField(choices=[('Device', 'Device'), ('Member', 'Member'), ('Admin', 'Admin')], default='Device', max_length=10),
        ),
    ]
