# Generated by Django 4.0.4 on 2022-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_device_remove_user_is_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('Device', 'Device'), ('Member', 'Member')], default=1, max_length=10),
        ),
    ]
