openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /StudySafe_Core/api/hkumembers/:
    get:
      operationId: listHKUMembers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HKUMember'
          description: ''
      tags:
      - StudySafe-Core
    post:
      operationId: createHKUMember
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HKUMember'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HKUMember'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HKUMember'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HKUMember'
          description: ''
      tags:
      - StudySafe-Core
  /StudySafe_Core/api/hkumembers/{uid}/:
    get:
      operationId: retrieveHKUMember
      description: ''
      parameters:
      - name: uid
        in: path
        required: true
        description: A unique value identifying this hku member.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HKUMember'
          description: ''
      tags:
      - StudySafe-Core
    put:
      operationId: updateHKUMember
      description: ''
      parameters:
      - name: uid
        in: path
        required: true
        description: A unique value identifying this hku member.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HKUMember'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HKUMember'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HKUMember'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HKUMember'
          description: ''
      tags:
      - StudySafe-Core
    patch:
      operationId: partialUpdateHKUMember
      description: ''
      parameters:
      - name: uid
        in: path
        required: true
        description: A unique value identifying this hku member.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HKUMember'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HKUMember'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HKUMember'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HKUMember'
          description: ''
      tags:
      - StudySafe-Core
    delete:
      operationId: destroyHKUMember
      description: ''
      parameters:
      - name: uid
        in: path
        required: true
        description: A unique value identifying this hku member.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - StudySafe-Core
components:
  schemas:
    HKUMember:
      type: object
      properties:
        uid:
          type: string
          maxLength: 10
        name:
          type: string
          maxLength: 150
      required:
      - uid
      - name
