# Generated by Django 4.0.4 on 2022-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueCode', models.CharField(db_column='Venue Code', max_length=20, unique=True)),
                ('Location', models.CharField(max_length=150)),
                ('Type', models.CharField(choices=[('LT', 'LT'), ('CR', 'CR'), ('TR', 'TR')], max_length=2)),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
