# Generated by Django 4.0.3 on 2022-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafe_Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hkumember',
            name='id',
        ),
        migrations.AlterField(
            model_name='hkumember',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
