# Generated by Django 4.0.3 on 2022-04-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafe_Core', '0002_remove_hkumember_id_alter_hkumember_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_code', models.CharField(max_length=20)),
                ('time_of_entry', models.DateTimeField()),
                ('time_of_exit', models.DateTimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySafe_Core.hkumember')),
            ],
        ),
    ]
