# Generated by Django 4.0.4 on 2022-04-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafe_Core', '0007_venues_alter_travelrecord_venue_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
