# Generated by Django 4.0.4 on 2022-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafe_Core', '0008_rename_venues_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecord',
            name='time_of_exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
